### ISSUE TITLE
How to trigger from an unlabeled issue?

### ISSUE THREAD

**Issue by rcorces** [dessant/label-actions#17]
This tools is amazing and is exactly what I have been wishing for. I'm able to get this workflow to work for labeled issues but I havent figured out how to trigger an action from an unlabeled issue. For example, I tried the following but it does not get triggered when an unlabeled issue is created:

```
unlabeled:
  # Post a comment
  comment: >
    This is an unlabeled issue post.
```

My workflow file does have triggers on labeled or unlabeled issues:
```
on:
  issues:
    types: [labeled, unlabeled]
  pull_request:
    types: [labeled, unlabeled]
  discussion:
    types: [labeled, unlabeled]
```

If this is explained somewhere in the documentation, I apologize for missing it. If not, perhaps you could add an example of triggering on an unlabeled issue as well. Thanks for maintaining such a useful tool!
