### ISSUE TITLE
fix: `ValidationError: "// REF" must be of type object`

### ISSUE THREAD

**Issue by jjangga0214** [dessant/label-actions#27]
Hi!

I wonder what this error means.

<img width="434" alt="스크린샷 2024-02-05 오후 9 21 32" src="https://github.com/dessant/label-actions/assets/28584151/112e9c43-3581-45b4-8cd6-9fb1feb740ae">

## Background: 

I wanted `safe-publish` label to be automatically unlabeled when it's labeled.
(Scenario: Human labels PR, and some workflows are run, and then the label is to be removed.)

**.github/workflows/main.yaml**:

```yaml
name: main

on:
  pull_request_target:
    types: [labeled]

jobs:
  main:
    permissions:
      contents: write 
      issues: write
      pull-requests: write 

    runs-on: ubuntu-latest

    steps:

      # - name: do something..... (Omitted for brevity)

      - name: unlabel
        if: contains(github.event.pull_request.labels.*.name, 'safe-publish')
        uses: dessant/label-actions@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

**.github/label-actions.yml**:

```yaml
'safe-publish':
  prs:
    unlabel:
      - 'safe-publish'
```
