### ISSUE TITLE
Advanced filters

### ISSUE THREAD

**Issue by m-kuhn** [dessant/label-actions#4]
Lovely tool!

One thing that would be nice is to be able to specify additional filter conditions to omit actions/comments under certain conditions.

E.g. (syntax is just a sample)

```yaml
issues:
  actions:
    enhancement:

      # Only comment with a funding request if it the funded label has not yet been set
      if: !funded

      comment: >
        This has been accepted as an enhancement request. Good job :+1:
        [Learn how to make it happen](https://make.it.happen/fundmenow).
```
